### ISSUE TITLE
4c) Use functions of 2-v) & vi) and analyse results

### ISSUE THREAD

**Issue by miamacarena** [iiiMatt/WiSe-2023-24#22]
Use functions of 2-v) & vi) and analyse visualizations and results: 

-visualization regarding 3 or 4 categorical variables 
-mosaicplot
-boxplot

**Comment by miamacarena** [comment]
Work flow:

- new branch emerging from analysis branch
- Add code into analysis.R
- pull request to merge with analysis branch

After we might bring our results together and add it to the read me.

**Comment by Loguy007** [comment]
I've finished and look forward to hearing from you.
