### ISSUE TITLE
Customize README.md

### ISSUE THREAD

**Issue by smnehong** [iiiMatt/WiSe-2023-24#31]
As one of the last things on this repository we should customize the README.md file that is displayed automatically when opening the repository.
I think it would be useful for it to contain:
- [x]  our contact information (name and uni mail address)
- [x]  a general overview of our conclusions from the data (after we finished discussion)
- [x]  a quick description what each file is for (sadly I wasn’t able to include this in the documentation)
- [x]  a guide on which script to run in which working directory to use our code

For our repo, it should be enough to just write bullet points starting with “-“ into the README file.

Feel free to comment additional things to be included in the README file or to object to any of the above proposals.

**Comment by helen-mza** [comment]
I added the names and file descriptions. See #33
