### ISSUE TITLE
2a- i) Suiting descriptive statistics for metric variables

### ISSUE THREAD

**Issue by miamacarena** [iiiMatt/WiSe-2023-24#6]
We are supposed to create a function that calculate suiting descriptive statistics for metric variables and give them back. 

Assigned it should be to either Neo or Helen. Please assign it to one of you two.

**Comment by helen-mza** [comment]
I thought about these statistics:
-Minimum
-Maximum 
-Mean
-Median
-Standard Deviation  

Do we need the Mode or the variance ?

**Comment by miamacarena** [comment]
Sounds good! I think it is better when we calculate mode just with the kategorical variables. And since you are planning on calculating the SD i dont think we need the variance either.
