### ISSUE TITLE
2a- ii) Suiting descriptive statistics for kategorial variables

### ISSUE THREAD

**Issue by miamacarena** [iiiMatt/WiSe-2023-24#7]
We are supposed to create a function that calculate suiting descriptive statistics for metric variables and give them back.

Assigned it should be to either Neo or Helen. Please assign it to one of you two.

**Comment by miamacarena** [comment]
We can also brainstorm here some statistics we want to calculate- keep excercise 4 in mind.

**Comment by smnehong** [comment]
I thought about calculating:
- mode
- empirical entropy

Then I would check if the factor is ordered in which case I would also calculate:
- median
- quartile deviation or median absolute deviation

**Comment by miamacarena** [comment]
Sounds good to me ! Great idea
