### ISSUE TITLE
2a - iii) descriptive bivariate statistics : relationship between two categorical variables

### ISSUE THREAD

**Issue by miamacarena** [iiiMatt/WiSe-2023-24#8]
We are supposed to create a function that calculates and outputs appropriate descriptive bivariate statistics for the relationship between two categorical variables. 

It should be assigned to either Mate, Johanna, Loic or me (Mia)

**Comment by miamacarena** [comment]
We can also brainstorm here some statistics we want to calculate- keep excercise 4 in mind.

**Comment by miamacarena** [comment]
I am thinking about applying a chi squared test and outputting beside the results also the contingency table.

**Comment by smnehong** [comment]
Great idea!

**Comment by Loguy007** [comment]
i've had a look at your work, it's well done and i think your idea is brilliant. personally, i was thinking of something else when i saw the title, but your idea of doing a statistical test is better.
